# Generated by Django 4.0.6 on 2023-02-09 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveBigIntegerField(auto_created=True)),
                ('emp_name', models.CharField(max_length=20)),
                ('ph_no', models.PositiveBigIntegerField()),
                ('emergency_no', models.PositiveBigIntegerField()),
                ('address', models.TextField(max_length=200, null=True)),
                ('position', models.CharField(max_length=50)),
                ('dob', models.DateField(null=True)),
                ('martial_status', models.CharField(max_length=10)),
                ('blood_gp', models.CharField(max_length=10)),
                ('job_title', models.CharField(max_length=30)),
                ('work_location', models.CharField(max_length=40)),
                ('date_join', models.DateField()),
                ('reporting_to', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=100)),
                ('prof_pic', models.ImageField(null=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField()),
                ('nature_of_leave', models.TextField(max_length=200)),
                ('first_day', models.CharField(max_length=20)),
                ('last_day', models.CharField(max_length=20)),
                ('number_of_days', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
